title:        Yphtach Lelkes
tagline:      ''
description:  'Assistant Professor of Political Communication. Amsterdam School of Communication Research. University of Amsterdam.'
url:          http://andhyde.com
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
analytics :
  provider : google
  google : 'UA-52779584-1'
  tracking_id : ''
  getclicky :
    site_id :

