title:        Yphtach Lelkes
tagline:      ''
description:  'Assistant Professor of Political Communication. Amsterdam School of Communication Research. University of Amsterdam.'
url:          http://ylelkes.com
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-52779584-1'
